site_name: Autonomous vehicles and robots software engineering
site_description: 'A course at Széchenyi István University, Győr, Hungary'
site_author: 'sze'
site_url: 'https://sze-info.github.io/avr/' # Uncomment to set a canonical URL
copyright: |
  &copy; Széchenyi István University 
docs_dir: docs/

repo_url: https://github.com/sze-info/avr/
nav:
  - Start: README.md
  - Curriculum:
    - 1. Introduction: 
      - introduction/README.md
      - introduction/practice.md
      - introduction/windows.md
      - introduction/copilot.md
      - introduction/linux.md
    - 2. ROS 2 concepts and install: 
      - ros2/README.md
      - ros2/practice.md
      - ros2/ubuntu.md
      - ros2/windows_subsystem.md
      - ros2/vscodegit.md
      - ros2/ros2_humble.md
    - 3. Sensing: 
      - sensing/README.md
      - sensing/practice.md
    - 4. ROS 2 advanced: 
      - ros2advanced/README.md
      - ros2advanced/ros2launch.md
      - ros2advanced/projects.md
      - ros2advanced/smallassignment.md
      - ros2advanced/semesterproject.md      
    - 5. Transformations: 
      - transformations/README.md
      - transformations/practice.md
    - 6. Perception:
      - perception/README.md
      - perception/practice.md
      - perception/practice_cluster.md
      - perception/ground_filter.md
      - perception/road_filter.md
      - perception/slam.md
      
    - 7. Simulation:
      - simulation/README.md
      - simulation/practice.md
      - simulation/gazebo_fortress.md
      - simulation/f1tenth_sim_a.md
    - 8. Planning:
      - planning/README.md
      - planning/practice.md
    - 9. Control:
      - control/README.md
      - control/ros2practice.md
    - 10. AI (artificial intelligence):
      - ai/README.md
      - ai/practice.md
    - 11. Safety V&V:
      - safety/README.md
      - safety/practice.md

  - Assignments:
    - assignments/README.md
    - assignments/small_assignment.md
    - assignments/semester_project.md
  - Self-paced:
    - ros2halado/py_cpp.md    
    - onallo/ros2git.md
    - onallo/linux.md
    - onallo/ros2launchmarker.md
    - onallo/mermaid.md
    - ros2halado/rqt.md    
    - ros2halado/qos.md    
    - ros2halado/mcap.md    
    - ros2halado/docker.md    
    - ros2halado/state.md    
    - ros2halado/vizualizacio.md    
    - ros2halado/pointcloud_to_grid.md
    - kalman_filter/README.md
    - kalman_filter/practice.md
  - Links:
    - links/README.md
  - Moodle: https://szelearning.sze.hu/course/view.php?id=13973
theme:
  name: 'material'
  favicon: 'assets/images/favicon.svg'
  palette:
    - scheme: youtube
      primary: 'custom'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      # primary: black
      primary: 'custom'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
  - search.suggest
  - content.code.copy
  - content.code.select
  - content.tabs.link
  - navigation.tabs         # Render top sections as tabs at the top.
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.

  - toc.follow
  icon:
    logo: 'material/robot-mower'
    repo: 'material/github'
extra_css:
- stylesheets/extra.css
# - https://unpkg.com/katex@0/dist/katex.min.css # KATEX
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://jkk-research/jkk-research.github.io'
  alternate:
    - name: Magyar
      link: https://sze-info.github.io/ajr/ 
      lang: hu
    - name: English
      link: https://sze-info.github.io/avr/ 
      lang: en
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg    
  - md_in_html
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - social:
      cards_layout: default/only/image
      cards_layout_options:
        background_image: 'assets/images/social1.png'
        background_color: "#43AEC5"
        color: "#ffffff" 
        font_family: Ubuntu